export hintQ2P1="MaKing files (or DIRectories) is pretty easy, you can make multiple on one line with that one simple command"
export hintQ2P2="UNZIPping files is easy, but MoVing files can be abit harder."
export hintQ2P3="MoVeing files isnt always about its location. Sometimes its its the designation"
export answerQ2P1="mkdir quests quests/quest1 quests/quest1/file1 quests/quest1/file2 quests/quest2 quests/quest2/game quests/quest3/"
export answerQ2P2="unzip <filename> | mv <current file location> <file destination>"
export answerQ2P3="mv quests/quest1/file1/file1.txt quests/quest1/file1/file1.py"